#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

INFO_TEXT="\e[1;32m[INFO]\e[0m"
ERROR_TEXT="\e[1;31m[ERROR]\e[0m"
WORKING_DIR=$(pwd)

if [ -f "client/package.json" ]; then
    LAST_COMMIT=$(git log -1 --pretty=format:"%B")
    echo "$LAST_COMMIT"
    OUTPUT_STRING=$(python -c "print(\"\"\"$LAST_COMMIT\"\"\".startswith('🚧'))")
    if [ $OUTPUT_STRING == 'True' ]; then
        exit 0
    else
        cd client
        yarn
        yarn build
    fi
else
    echo -e "$ERROR_TEXT 'client/package.json' does not exist."
    exit 1
fi
